import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bird, Menu, ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const navigationItems = [
  { title: "SOLUTIONS", href: "#" },
  { title: "INDUSTRIES", href: "#" },
  { title: "RESOURCES", href: "#" },
  { title: "ABOUT US", href: "#" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="container mx-auto px-4">
            <div className="flex h-16 items-center justify-between">
              <a href="#" className="flex items-center gap-2">
                <div className="flex items-center space-x-2">
                  <Bird className="h-8 w-8" />
                  <span className="font-mono text-xl font-bold">Myna UI</span>
                </div>
              </a>

              <nav className="hidden md:flex items-center space-x-8">
                {navigationItems.map((item) => (
                  <a
                    key={item.title}
                    href={item.href}
                    className="text-sm font-mono text-foreground hover:text-[#FF6B2C] transition-colors"
                  >
                    {item.title}
                  </a>
                ))}
              </nav>

              <div className="flex items-center space-x-4">
                <Button
                  variant="default"
                  className="rounded-none hidden md:inline-flex bg-[#FF6B2C] hover:bg-[#FF6B2C]/90 font-mono"
                >
                  GET STARTED <ArrowRight className="ml-1 w-4 h-4" />
                </Button>
                <Sheet>
                  <SheetTrigger asChild>
                    <Button variant="ghost" size="icon" className="md:hidden">
                      <Menu className="h-5 w-5" />
                      <span className="sr-only">Toggle menu</span>
                    </Button>
                  </SheetTrigger>
                  <SheetContent>
                    <nav className="flex flex-col gap-6 mt-6">
                      {navigationItems.map((item) => (
                        <a
                          key={item.title}
                          href={item.href}
                          className="text-sm font-mono text-foreground hover:text-[#FF6B2C] transition-colors"
                        >
                          {item.title}
                        </a>
                      ))}
                      <Button className="cursor-pointer rounded-none bg-[#FF6B2C] hover:bg-[#FF6B2C]/90 font-mono">
                        GET STARTED <ArrowRight className="ml-1 w-4 h-4" />
                      </Button>
                    </nav>
                  </SheetContent>
                </Sheet>
              </div>
            </div>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
